Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: ApiGateway
      StageName: Prod
      DefinitionBody: !Transform
        Name: AWS::Include
        Parameters:
          Location: api.yaml
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''*'''
  GetItems:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetItems
      CodeUri: src/GetItems
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 2048
      Timeout: 30
      Tracing: Active
      Events:
        ApiGatewayGETitems:
          Type: Api
          Properties:
            Path: /items
            Method: GET
            RestApiId: !Ref ApiGateway
      Environment:
        Variables:
          ITEMS_TABLE_NAME: !Ref Items
          ITEMS_TABLE_ARN: !GetAtt Items.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Items
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  GetItemsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetItems}
  Items:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES